public with sharing class TheCat
{
    public TheCat()
    {
        system.debug('Hey cat!');
        system.debug('Cat! Over here!');
        system.debug('Rimmer!');
        system.debug('We are flubbed!');
        system.debug('Lister!');
        system.debug('Where are you Lister?!');
        system.debug('Lister, hello?!');
        system.debug('Over here Rimmer!');
        system.debug('Hi');
        system.debug('Bye');
    }
}
